import type { AgentDefinition } from "./types.ts";

export const CTO_ARCHITECT: AgentDefinition = {
  id: "cto_architect",
  name: "CTO / AI Systems Architect",
  role: "Technical strategy and architecture owner",
  mission: "Own technical strategy and architecture.",
  status: "ACTIVE",
  capabilities: ["ARCHITECTURE"],
  allowedTools: [],
  prohibitedTools: ["browser", "filesystem", "terminal", "http", "mcp"],
  allowedPermissions: [],
  prohibitedPermissions: [
    "WEB_SEARCH",
    "WEB_READ",
    "WEB_NAVIGATE",
    "WEB_CLICK",
    "WEB_TYPE",
    "WEB_DOWNLOAD",
    "WEB_UPLOAD",
    "FILESYSTEM_READ",
    "FILESYSTEM_WRITE",
    "TERMINAL_EXECUTE",
    "API_REQUEST",
    "MCP_EXECUTE",
  ],
  handoffTargets: [
    "research_intelligence",
    "product_ux",
    "principal_engineer",
    "growth_analytics",
  ],
  riskLevel: "MEDIUM",
};

export const RESEARCH_INTELLIGENCE: AgentDefinition = {
  id: "research_intelligence",
  name: "Research Intelligence",
  role: "External knowledge acquisition and verification",
  mission: "Acquire and verify external knowledge.",
  status: "ACTIVE",
  capabilities: ["RESEARCH", "WEB_RESEARCH", "EVIDENCE_COLLECTION"],
  allowedTools: ["browser", "http"],
  prohibitedTools: ["filesystem", "terminal", "mcp"],
  allowedPermissions: ["WEB_SEARCH", "WEB_READ", "WEB_NAVIGATE"],
  prohibitedPermissions: [
    "WEB_CLICK",
    "WEB_TYPE",
    "WEB_DOWNLOAD",
    "WEB_UPLOAD",
    "FILESYSTEM_WRITE",
    "TERMINAL_EXECUTE",
    "MCP_EXECUTE",
  ],
  handoffTargets: [
    "cto_architect",
    "product_ux",
    "principal_engineer",
    "growth_analytics",
  ],
  riskLevel: "MEDIUM",
};

export const PRODUCT_UX: AgentDefinition = {
  id: "product_ux",
  name: "Product / UX",
  role: "Product and user-experience design",
  mission: "Translate customer problems into useful products.",
  status: "ACTIVE",
  capabilities: ["PRODUCT_STRATEGY", "UX_DESIGN"],
  allowedTools: [],
  prohibitedTools: ["browser", "filesystem", "terminal", "http", "mcp"],
  allowedPermissions: [],
  prohibitedPermissions: [
    "WEB_CLICK",
    "WEB_TYPE",
    "WEB_DOWNLOAD",
    "WEB_UPLOAD",
    "FILESYSTEM_WRITE",
    "TERMINAL_EXECUTE",
    "API_REQUEST",
    "MCP_EXECUTE",
  ],
  handoffTargets: [
    "cto_architect",
    "research_intelligence",
    "principal_engineer",
    "growth_analytics",
  ],
  riskLevel: "MEDIUM",
};

export const PRINCIPAL_ENGINEER: AgentDefinition = {
  id: "principal_engineer",
  name: "Principal AI Full-Stack Engineer",
  role: "Production software implementation",
  mission: "Turn approved architecture and product requirements into production software.",
  status: "ACTIVE",
  capabilities: ["ENGINEERING", "CODE", "TESTING"],
  allowedTools: ["filesystem", "terminal"],
  prohibitedTools: ["browser", "http", "mcp"],
  allowedPermissions: ["FILESYSTEM_READ", "FILESYSTEM_WRITE", "TERMINAL_EXECUTE"],
  prohibitedPermissions: [
    "WEB_SEARCH",
    "WEB_READ",
    "WEB_NAVIGATE",
    "WEB_CLICK",
    "WEB_TYPE",
    "WEB_DOWNLOAD",
    "WEB_UPLOAD",
    "API_REQUEST",
    "MCP_EXECUTE",
  ],
  handoffTargets: [
    "cto_architect",
    "research_intelligence",
    "product_ux",
    "growth_analytics",
  ],
  riskLevel: "HIGH",
};

export const GROWTH_ANALYTICS: AgentDefinition = {
  id: "growth_analytics",
  name: "Growth / Analytics",
  role: "Growth measurement and improvement",
  mission: "Measure and improve business growth.",
  status: "ACTIVE",
  capabilities: ["ANALYTICS", "SEO", "GROWTH"],
  allowedTools: ["browser"],
  prohibitedTools: ["filesystem", "terminal", "http", "mcp"],
  allowedPermissions: ["WEB_SEARCH", "WEB_READ"],
  prohibitedPermissions: [
    "WEB_NAVIGATE",
    "WEB_CLICK",
    "WEB_TYPE",
    "WEB_DOWNLOAD",
    "WEB_UPLOAD",
    "FILESYSTEM_WRITE",
    "TERMINAL_EXECUTE",
    "API_REQUEST",
    "MCP_EXECUTE",
  ],
  handoffTargets: [
    "cto_architect",
    "research_intelligence",
    "product_ux",
    "principal_engineer",
  ],
  riskLevel: "MEDIUM",
};

export const INITIAL_AGENTS: readonly AgentDefinition[] = [
  CTO_ARCHITECT,
  RESEARCH_INTELLIGENCE,
  PRODUCT_UX,
  PRINCIPAL_ENGINEER,
  GROWTH_ANALYTICS,
];
